name: Actualización inventario Bigcommerce

on:
  schedule:
    - cron: '0 2 * * *'  # Ejecuta todos los días a las 02:00 UTC
  workflow_dispatch:  

jobs:
  build-and-run:
    runs-on: windows-latest  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'  

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release

      - name: Run application with environment variables
        run: |
          export FTP_HOST=${{ secrets.FTP_HOST }}
          export FTP_USER=${{ secrets.FTP_USER }}
          export FTP_PASS=${{ secrets.FTP_PASS }}
          export BIGCOMMERCE_API_URL=${{ secrets.BIGCOMMERCE_API_URL }}
          export BIGCOMMERCE_TOKEN=${{ secrets.BIGCOMMERCE_TOKEN }}
          dotnet run --configuration Release
